name: CI/CD MLflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Sesuaikan path agar menunjuk ke file di dalam folder MLproject
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn joblib

      # Perhatikan: kita menjalankan folder "MLproject"
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local
      
      # Step 1: Ambil run_id terbaru
      - name: Get latest MLflow run_id
        # Kita berikan ID pada step ini agar outputnya bisa dipanggil
        id: get_id
        run: |
          # Ambil folder terbaru di mlruns/0 yang bukan sistem MLflow
          ID=$(ls -t mlruns/0 | grep -vE "meta.yaml|models" | head -n 1)
          
          # Validasi jika kosong
          if [ -z "$ID" ]; then
            echo "Error: Run ID tidak ditemukan di mlruns/0"
            exit 1
          fi
          
          # Simpan ke GITHUB_ENV (untuk shell) dan set-output (untuk konteks GitHub)
          echo "RUN_ID=$ID" >> $GITHUB_ENV
          echo "run_id=$ID" >> $GITHUB_OUTPUT
          echo "Berhasil mendapatkan Run ID: $ID"

      # Step 2: Build Docker Model
      - name: Build Docker Model
        run: |
          # Gunakan variabel yang sudah kita simpan di GITHUB_ENV
          # Tambahkan satu garis miring (/) setelah 'runs:'
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "cc"
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          # Menggunakan variabel rahasia untuk username agar lebih aman
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
